version: "3"
services:
    new-lps-website:
        restart: always
        ports:
            - 5120:4000
        env_file:
            - .env
        image: ghcr.io/redstonewizard08/new-lps-website
